# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'feat/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build, Test and Package
        run: mvn -B clean verify package
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Java docs
        run: mvn -B javadoc:javadoc
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload javadoc
        uses: actions/upload-artifact@v4
        with:
          name: apidocs
          path: target/site/apidocs/
        env:
          GITHUB_TOKEN: ${{ github.token }}
